#!/bin/bash
for i in `seq 1 15`;
do
	echo $i:
	echo
	cat ~/svc/results/text/s2.srr505.${i}.nord/tandemDuplications.bedpe | cut -f1,2,6 | awk '$3 > $2 && $2 >0' > tds
	cat ~/svc/results/text/s2.srr505.${i}.nord/insertions.bedpe | cut -f1,2,3 | awk '$3 > $2 && $2 >0' > inss 
	cat tds inss > dups
	bedtools intersect -wa -wb -f $1 -a dups -b 1000Genomes/dups.merged.bed | cut -f4-6 | sort | uniq | wc -l
	bedtools intersect -wa -wb -f $1 -a dups -b 1000Genomes/dups.merged.bed | sort | uniq | cut -f1-3 | sort | uniq -d| wc -l
	echo "Duplicated uniq -d calls (many svc to 1 truth):"; bedtools intersect -wa -wb -f $1 -a dups -b 1000Genomes/dups.merged.bed | sort | uniq | cut -f4-6 | sort | uniq -d| wc -l
	echo "Total calls:"; wc -l dups
	echo
done
