#!/usr/bin/env bash
set -eu

LIB_INV=1
SUBSAMPLE_DISC=0 #use ONLY if code slow. Should rarely be needed.
VERBOSE=0
PE_ALMT_COMB_THRESH=20
AS_THRESH=0
MAP_THRESH=1
MAP_THRESH_U=10
MQ_SR=10
AS_RELATIVE_THRESH=2
NMATCH_RELATIVE_THRESH=0
NMATCH_PCT_THRESH=0
CALC_THRESH=1000000
SIG_THRESH=.9985
RDS=0
MAX_CL_COMB_GAP=450
SLOP_PE=0
MIN_PE_BPMARGIN=20
SLOP_SR=8
REF_RATE_SR=0
RO=0.7
REF_RATE_PE=5
MIN_UNIQUE_SUPP=3
MIN_CS=3
MIN_VS_SR=3
SAM=samtools
BAMFILE=
S_PATH=
RD_FILE="none"
DISC_FILE=
THREADS=1
DISC_IS_NS=0
IGNORE_BED="none"
IGNORE_CHR="none"
AS_CALC_THRESH=.999
DISC_ENHANCER=1.67
RD_VAR_INDEX=3000000
RD_FRAG_INDEX=100000000
RD_MARGIN=0
MIN_SIZE_INS_SR=30
SLOP_RD=250
RD_MQU=10
MIN_SRtoPE_SUPP=2
DEL_CN_SUPP_THRESH=.6 
DUP_CN_SUPP_THRESH=1.4
DEL_CN_SUPP_THRESH2=.125
DUP_CN_SUPP_THRESH2=1.75
DENOVO_RD=1
PILEUP_THRESH=500.0
NH_REGIONS_FILE="none"
WORK_DIR=.
SPLIT_INS=0

usage()
{
cat << EOF
usage: $0 [options]

Options (please use short options for now):
    -h 				(this menu)
    -a|--bamfile 		(*REQUIRED: path of position-sorted bam file)
    -b|--bam_ns 		(*REQUIRED: path of name-sorted bam file)
    -z|--disc			(*REQUIRED: path of BAM file containing all discordant pairs extracted from above. See README) 
    -A|ns			(Set this to 0 if discordant file above is not name-sorted; def = 1)
    -B|--threads		(Number of available cores; def = 1)
    -C|--ignoreB		(BED file in format "chr start stop", w/o ANY headers, containing reference regions to ignore in forming variants)
    -D|--ignoreChr		(file containing names of chromosomes, 1 per line,  whose alignments should be completely ignored)
    -c|--read_thresh 		(max number of discordant read mappings a single PE fragment mate can have for it not to be ignored in uniqeness-based set cover, default = 20)
    -d|--match_thresh 		(min threshold of ratio of a given secondary alignment's score with AS of primary alignment needed for this secondary alignment to be considered/used in set cover, def = 2, recommended = .95 if using secondary alignments)
    -e|--n_match_thresh 	(same as above for number of base pair matches in alignment, instead of AS, def = 0)
    -f|--n_pct_thresh 		(min ratio of matching bases in a given alignment to read length required for read to be used in analysis, default =  0)
    -g|--calc_thresh 		(max entries of bamfile used to ascertain stats like coverage, mean insert length etc., def = 1,000,000)
    -i|--sam_path 		(complete path to "samtools" command, including /samtools, if not on path)
    -m|--rd_signal 		(SET to 1 if using -x; whether or not to use CNV calls from a third party tool to support variants called by VARSEC, e.g. if CN file is not available set this to 0; def = 1)
    -n|--rec_overlap		(min reciprocal overlap needed with CN region to boost/give more weight to intermediate PE-supported SV)
    -q|--disj_thresh		(number of unique fragment mappings required in variant set to pick set as claimed SV, def = 4)
    -r|--splitter_path		(*REQUIRED: path to split-reads bam file)
    -s|--splitter_slop		(margin used in differentiating split-read break points from one another; def = 10)
    -u|--min_cluster		(the minimum number of reads supporting a cluster required for it to be considered in the analysis, def = 3)
    -x				(-m must be set if using this; path to file containing CNVs)
    -y				(binary switch; set to 0 if wish to see only those variants whose supporting fragments do not map at all to other variants, def = 1)
    -F				(set to 1 if wish to see DE NOVO read depth calls; dependent on -m; def = 1)
    -I                          (file containing 3 cols -- chr, start, stop -- defining good regions in the reference to use when calculating pile up)
    -L				(liberal inversion reporting: if a split read and 1 paired end cluster support an inversion, report it; if flag is 0, 2 opp. orientation paired-end clusters required to report inversion)					
    -W				(working directory)
    -S				(Set to 1 to split copy-paste or cut-paste insertion calls into diploid DEL, TD variants if indicated by local coverage in variant region;def=0)
    -V              (Turn on verbose output;def=off)
EOF
}

versionC(){
cat $(dirname "$0")/../VERSION
}

while getopts “hvLVa:b:c:d:e:f:g:i:j:k:l:m:n:o:p:q:r:s:u:v:w:x:z:A:B:C:D:F:G:I:W:S:” OPTION
do

     case $OPTION in
	    h)
	    usage
	    exit 1
	    ;;	
        a)
	    BAMFILE="$OPTARG"
	    ;;
	    c)
	    PE_ALMT_COMB_THRESH="$OPTARG"
	    ;;
	    d)
	    AS_RELATIVE_THRESH="$OPTARG"
	    ;;
	    e)
	    NMATCH_RELATIVE_THRESH="$OPTARG"
	    ;;
	    f)
	    NMATCH_PCT_THRESH="$OPTARG"
	    ;;
	    g)
	    CALC_THRESH="$OPTARG"
	    ;;
	    i)
        SAM="$OPTARG"
        ;;
	    j)
	    MIN_PE_BPMARGIN="$OPTARG"
	    ;;
	    k)
	    REF_RATE_SR="$OPTARG"
	    ;;
	    l)
	    SLOP_PE="$OPTARG"
	    ;;
	    m)
        RDS="$OPTARG"
        ;;
	    n)
	    RO="$OPTARG"
	    ;;
	    o)
	    MAX_CL_COMB_GAP="$OPTARG"
	    ;;
	    p)
	    REF_RATE_PE="$OPTARG"
	    ;;
	    q)
	    MIN_UNIQUE_SUPP="$OPTARG"
	    ;;
	    r)
	    S_PATH="$OPTARG"
	    ;;
	    s)
	    SLOP_SR="$OPTARG"
	    ;;
	    u)
	    MIN_CS="$OPTARG"
	    ;;
	    v)
	    versionC
	    exit 1
	    ;;
	    x)
	    RD_FILE="$OPTARG"
	    ;;
	    z)
        DISC_FILE="$OPTARG"
        ;;
	    A)
        DISC_IS_NS="$OPTARG"
        ;;
	    B)
        THREADS="$OPTARG"		
	    ;;
	    C)
	    IGNORE_BED="$OPTARG"
	    ;;
	    D)
	    IGNORE_CHR="$OPTARG"
	    ;;
	    F)
        DENOVO_RD="$OPTARG"
        ;;
	    G)
        SIG_THRESH="$OPTARG"
        ;;
	    I)
        NH_REGIONS_FILE="$OPTARG"
        ;;
	    W)
        WORK_DIR="$OPTARG"
        ;;
	    S)
        SPLIT_INS="$OPTARG"
        ;;
        V)
        VERBOSE=1
        ;;
        L)
        SUBSAMPLE_DISC=1
        ;;
	    ?)
	    echo "Option not recognized."
	    exit
	    ;;
     esac
done

if [[ -z $BAMFILE ]] || [[ -z $S_PATH ]]
then
     usage
     echo "Please provide paths to input BAM files as well as SAMTOOLS: required option fields are -a, -b, -z, -r."
     exit 1
fi

echo WD IS $WORK_DIR
mkdir -p $WORK_DIR
mkdir -p $WORK_DIR/SVC_results
mkdir -p $WORK_DIR/SVC_debug
rm -f $WORK_DIR/SVC_debug/*
rm -f $WORK_DIR/SVC_results/*

#IF disc BAM not ready
#time ($SAM view -@32 -F 3586 -b -o $WORK_DIR/SVC_debug/disc.bam $BAMFILE) #34m
#DISC_FILE=$WORK_DIR/SVC_debug/disc.bam

#Remove next 2 comments when done testing
time ($SAM view -@ $THREADS -f 64 -b -o $WORK_DIR/SVC_debug/aln1s.us.bam $DISC_FILE) #4m
time ($SAM view -@ $THREADS -f 128 -b -o $WORK_DIR/SVC_debug/aln2s.us.bam $DISC_FILE) # 4m
 
if [ $DISC_IS_NS -eq 1 ]
then
	mv $WORK_DIR/SVC_debug/aln1s.us.bam $WORK_DIR/SVC_debug/aln1s.bam # change back to al1ns_u.bam etc
	mv $WORK_DIR/SVC_debug/aln2s.us.bam $WORK_DIR/SVC_debug/aln2s.bam
else
	$SAM sort -n -@ $THREADS $WORK_DIR/SVC_debug/aln1s.us.bam > $WORK_DIR/SVC_debug/aln1s.bam
	$SAM sort -n -@ $THREADS $WORK_DIR/SVC_debug/aln2s.us.bam > $WORK_DIR/SVC_debug/aln2s.bam
fi

SRC=$(dirname "$0")
CURR_DIR=$PWD

$SRC/form_clusters.sh $BAMFILE $PE_ALMT_COMB_THRESH $AS_RELATIVE_THRESH $NMATCH_RELATIVE_THRESH \
    $CALC_THRESH $NMATCH_PCT_THRESH $MIN_CS $MIN_PE_BPMARGIN $IGNORE_BED $IGNORE_CHR $MAP_THRESH \
    $AS_THRESH $SIG_THRESH $AS_CALC_THRESH $DISC_ENHANCER $WORK_DIR $SRC $VERBOSE $SUBSAMPLE_DISC
$SRC/run_PE.sh $MIN_CS $MAX_CL_COMB_GAP $SLOP_PE $REF_RATE_PE $MIN_UNIQUE_SUPP $BAMFILE $MAP_THRESH_U \
    $RD_VAR_INDEX $RD_FRAG_INDEX $DEL_CN_SUPP_THRESH $DUP_CN_SUPP_THRESH $WORK_DIR \
    $SRC $VERBOSE # can replace $MIN_CS here with another value and run these 2 steps with
    #new threshold rather than rerun whole cluster formation sequence. In this case, simply
    #comment out previous line and run varsecer.
$SRC/run_RD_SR.sh $S_PATH $SLOP_SR $REF_RATE_SR $RO $MIN_UNIQUE_SUPP $RDS $RD_FILE $IGNORE_CHR $MAP_THRESH_U $MQ_SR $MIN_VS_SR $BAMFILE $RD_VAR_INDEX $RD_FRAG_INDEX $RD_MARGIN $MIN_SIZE_INS_SR $SLOP_RD $RD_MQU $MIN_SRtoPE_SUPP $DEL_CN_SUPP_THRESH $DUP_CN_SUPP_THRESH $DENOVO_RD $DEL_CN_SUPP_THRESH2 $DUP_CN_SUPP_THRESH2 $PILEUP_THRESH $NH_REGIONS_FILE $LIB_INV $WORK_DIR $SRC $SPLIT_INS $VERBOSE $THREADS
cd $PWD
